"""empty message

Revision ID: e474210d3b21
Revises: 608aee6f6468
Create Date: 2023-04-16 22:51:02.617637

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e474210d3b21'
down_revision = '608aee6f6468'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('innovation',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=250), nullable=False),
    sa.Column('url_file', sa.String(length=250), nullable=False),
    sa.Column('url_imgage', sa.String(length=250), nullable=False),
    sa.Column('public_id', sa.String(length=100), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('innovation')
    # ### end Alembic commands ###
